version: '3.8'

services:
  # 1. Запуск реальной базы данных PostgreSQL
  postgres-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pet_project
    ports:
      - "5432:5432"
    volumes:
      # Docker возьмет ваш файл из draw.io и автоматически создаст таблицы
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # 2. Автоматический генератор API (читает таблицы БД и делает из них микросервис)
  api-service:
    image: postgrest/postgrest:v12.0.0
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: "postgres://user:password@postgres-db:5432/pet_project"
      PGRST_DB_SCHEMA: "public"
      PGRST_DB_ANON_ROLE: "user" # используем суперпользователя для простоты тестов
    depends_on:
      - postgres-db

  # 3. Красивый графический веб-интерфейс для тестов (Swagger)
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      SWAGGER_JSON: /app/openapi.yaml
    volumes:
      - ./openapi.yaml:/app/openapi.yaml
